// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmyxkowhehuslmnoumjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZteXhrb3doZWh1c2xtbm91bWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MzkyMzMsImV4cCI6MjA1OTExNTIzM30.3nCSiTB7yjq-9uuPS16j7UxuBVSNWCN3sSsjtW8JOAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);